name: Deploy to S3
permissions:
  contents: read

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Setup aws-exports.js
        run: echo $AWS_EXPORTS_JS >> ./src/aws-exports.js
        shell: bash
        env:
          AWS_EXPORTS_JS: ${{secrets.AWS_EXPORTS}}
      - name: Setup env
        run: echo $REACT_APP_STRIPE_PK >> ./.env;echo $REACT_APP_PRICE_MO >> ./.env;echo $REACT_APP_PRICE_YR >> ./.env;echo $REACT_APP_ACCESS_CODE >> ./.env
        shell: bash
        env:
          REACT_APP_STRIPE_PK: ${{secrets.REACT_APP_STRIPE_PK}}
          REACT_APP_PRICE_MO: ${{secrets.REACT_APP_PRICE_MO}}
          REACT_APP_PRICE_YR: ${{secrets.REACT_APP_PRICE_YR}}
          REACT_APP_ACCESS_CODE: ${{secrets.REACT_APP_ACCESS_CODE}}
      - name: Yarn Install
        run: yarn install
        env:
          CI: ''
      - name: Build
        run: npm run build
        env:
          CI: ''
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}
      - name: Deploy static site to S3 bucket
        run: aws s3 sync build s3://${{ secrets.S3_BUCKET }} --delete
